<?php

namespace lesha724\Notification\widgets;

use lesha724\Notification\helper\AlertsWidget;
use yii\bootstrap\Alert;

/**
 * Bootstrap alert
 */
class BootstrapAlert extends AlertsWidget
{
    /**
     * @var array the alert types configuration for the flash messages.
     * This array is setup as $key => $value, where:
     * - $key is the name of the session flash variable
     * - $value is the array:
     *       - class of alert type (i.e. danger, success, info, warning)
     *       - icon for alert
     */
    public $alertTypes = [
        'bootstrap-error' => [
            'class' => 'alert-danger',
            'icon' => '<i class="icon glyphicon glyphicon-ban-circle"></i>',
        ],
        'bootstrap-danger' => [
            'class' => 'alert-danger',
            'icon' => '<i class="icon glyphicon glyphicon-ban-circle"></i>',
        ],
        'bootstrap-success' => [
            'class' => 'alert-success',
            'icon' => '<i class="icon glyphicon glyphicon-ok"></i>',
        ],
        'bootstrap-info' => [
            'class' => 'alert-info',
            'icon' => '<i class="icon glyphicon glyphicon-exclamation-sign"></i>',
        ],
        'bootstrap-warning' => [
            'class' => 'alert-warning',
            'icon' => '<i class="icon glyphicon glyphicon-warning-sign"></i>',
        ],
    ];

    /**
     * @var array the options for rendering the close button tag.
     */
    public $closeButton = [];

    /**
     * Initializes the widget.
     * This method will register the bootstrap asset bundle. If you override this method,
     * make sure you call the parent implementation first.
     */
    public function init()
    {
        parent::init();
    }

    public function run(){
        parent::run();
    }

    protected function _runAlert($data, $type, $message, $appendCss)
    {
        parent::_runAlert($data, $type, $message, $appendCss); // TODO: Change the autogenerated stub

        $this->options['class'] = $this->alertTypes[$type]['class'] . $appendCss;

        $this->options['id'] = $this->getId() . '-' . $type;

        echo Alert::widget([
            'body' => $this->alertTypes[$type]['icon'] . $message,
            'closeButton' => $this->closeButton,
            'options' => $this->options,
        ]);
    }

}
